name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test puppeteer
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Test action with node 10
        uses: ./
      - name: Test action with node 12
        uses: ./
        with:
          node-version: '12'
      - name: Test action with node 14
        uses: ./
        with:
          node-version: '14'
      - name: Test action with node 15
        uses: ./
        with:
          node-version: '15'

