name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Test action
        uses: ./
        id: puppeteer-test
        with:
          files: test/test.js  # The test generates a test.pdf file in the home directory the steps below are used to verify the contents of the pdf file.

      - name: Copy test output
        uses: tj-actions/docker-cp@v2
        with:
          container: ${{ steps.puppeteer-test.outputs.container-id }}
          source: ${{ steps.puppeteer-test.outputs.home }}/test.pdf  # <-- Replace this input if copied or Remove this step
          destination: test.pdf  # <-- Replace this input if copied or Remove this step

      - name: Display contents of test.pdf  # <-- Replace this file name if copied or Remove this step
        run: cat test.pdf  # <-- Replace this file name if copied or Remove this step
